api/urls.py
from django.urls import path
from .views import RunDetectionView

app_name = 'api'

urlpatterns = [
    path('run_detection', RunDetectionView.as_view(), name='run')
]

darknetweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from detections import urls as urls_detections
from api import urls as urls_api
from .settings import MEDIA_ROOT, MEDIA_URL

media_url = static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls_detections)),
    path('api/', include(urls_api))
] + media_url

detections/urls.py
from django.urls import path
from .views import HomeView, NewDetectionView, DetectionListView

app_name = 'detections'

urlpatterns = [
    path('', HomeView, name='home'),
    path('detections', DetectionListView, name='list'),
    path('new_detection', NewDetectionView, name='new')
]

api/models.py
from django.db import models

detections/models.py
from django.db import models

class DetectionRequest(models.Model):
    created_time = models.DateTimeField()
    original_image = models.ImageField(upload_to="images/originals/")

    def __str__(self):
        return f"{self.created_time}"

    class Meta:
        db_table = 'DetectionRequest'
        verbose_name = 'DetectionRequest'
        verbose_name_plural = 'DetectionRequests'

class DetectionResult(models.Model):
    created_time = models.DateTimeField()
    duration = models.IntegerField()
    object_count = models.IntegerField()
    tag_count = models.IntegerField()
    image_width = models.IntegerField()
    image_height = models.IntegerField()
    tagged_image = models.ImageField(upload_to="images/tagged/")
    human_readable = models.CharField(max_length=500)
    detection_request = models.OneToOneField(DetectionRequest, on_delete=models.CASCADE, primary_key=True,)

    def __str__(self):
        return f"{self.created_time} ({self.object_count} objects, {self.duration / 100} seconds)"

    class Meta:
        db_table = 'DetectionResponse'
        verbose_name = 'DetectionResponse'
        verbose_name_plural = 'DetectionResponses'

class DetectableObject(models.Model):
    tag = models.CharField(max_length=50, primary_key=True)
    singular = models.CharField(max_length=50)
    plural = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.tag} ({self.singular}"

    class Meta:
        db_table = 'DetectableObject'
        verbose_name = 'DetectableObject'
        verbose_name_plural = 'DetectableObjects'
        
class DetectedObject(models.Model):
    POSITION_CHOICES = [
        (0, 'TOP'),
        (0, 'MIDDLE')
    ]

    tag = models.ForeignKey(DetectableObject, on_delete=models.CASCADE)
    accuracy_rate = models.DecimalField(max_digits=22, decimal_places=16)
    x_right = models.DecimalField(max_digits=22, decimal_places=16)
    x_left = models.DecimalField(max_digits=22, decimal_places=16)
    y_right = models.DecimalField(max_digits=22, decimal_places=16)
    y_left = models.DecimalField(max_digits=22, decimal_places=16)
    #overall_position = models.
    detection = models.ForeignKey(DetectionResult, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.tag} ({self.detected_time})"

    class Meta:
        db_table = 'DetectedObject'
        verbose_name = 'DetectedObject'
        verbose_name_plural = 'DetectedObjects'

api/views.py
from django.utils import timezone
from rest_framework.parsers import FileUploadParser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from .serializers import DetectionRequestSerializer
from detections.models import DetectionRequest
from yolopy.yolo import YoloNetwork

class RunDetectionView(APIView):
    parser_class = (FileUploadParser,)

    def post(self, request, *args, **kwargs):
        request.data['created_time'] = timezone.now()
        file_serializer = DetectionRequestSerializer(data=request.data)

        if file_serializer.is_valid():
            network = YoloNetwork.get_instance()

            file_serializer.save()

            print(network.detect_objects(request.data.original_image))

            return Response(file_serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def start_detections(self):
        pass

detections/views.py
from django.shortcuts import render
from .models import DetectionRequest

# Create your views here.

def HomeView(request):
    return render(request, 'detections/home.html')

#class NewDetectionView(CreateView):
    #model = DetectionRequest

def DetectionListView(request):
    data = {
        "detections" : DetectionRequest.objects.all()
    }

    return render(request, 'detections/detection_list.html', data)

def NewDetectionView(request):
    return render(request, 'detections/new_detection.html')

templates/detections/detection_list.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="ui items">
    {% for detection in detections %}
    <div class="item">
        <div class="image">
            <img src="{{detection.original_image.url}}">
        </div>
        <div class="content">
            <a class="header">{{detection.created_time}}</a>
        <div class="meta">
            <span>7 objects detected</span>
        </div>
        <div class="description">
            <p>2 cars, 3 coffee cups and 2 bikes</p>
        </div>
        <div class="extra">
            3.45 seconds
        </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

templates/detections/home.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="ui text container">
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <img class="ui medium left floated image" data-src="assets/images/wireframe/square-image.png">
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
        <img class="ui medium right floated image" data-src="assets/images/wireframe/square-image.png">
        Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <img class="ui medium left floated image" data-src="assets/images/wireframe/square-image.png">
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
        <img class="ui medium right floated image" data-src="assets/images/wireframe/square-image.png">
        Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
      </div>
{% endblock content %}

templates/detections/new_detection.html
{% extends "layouts/base.html" %}

{% block content %}

<form action="{% url 'api:run' %}" method="post" enctype="multipart/form-data" id="detect-form">
    Select image to upload:
    <input type="file" name="original_image" id="original_image">
    <input type="submit" value="Upload Image" name="submit">
</form>

{% endblock content %}

{% block script %}

<script>
    $( "#detect-form" ).submit(function( event ) {
        event.preventDefault();

        var form = $(this);
        var data = new FormData(form[0]);
        var url = form.attr( "action" );

        $.ajax({
            url: url,
            type: 'post',
            data: data,
            cache: false,
            contentType: false,
            processData: false,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            },
            success: function (data, status) {
                console.info(data);
                console.info(status);
            }
        });

    });
</script>
  
{% endblock script %}

templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DarkNet Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
</head>

<body>
    <div class="ui main text container">
        <br>
        <h1 class="ui header">DarkNet Web</h1>
        <p>Object detection in images</p>
    </div>

    <div class="ui borderless main menu" style="">
        <div class="ui text container">
            <a href="{% url 'detections:home' %}" class="header item">Home</a>
            <a href="{% url 'detections:list' %}" class="item">Detections</a>
            <a href="{% url 'detections:new' %}" class="item">New Detection</a>
        </div>
    </div>

    <div class="ui text container">
        {% block content %}{% endblock content %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% block script %}{% endblock script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <script>
        $(document)
            .ready(function () {

                // fix main menu to page on passing
                $('.main.menu').visibility({
                    type: 'fixed'
                });
                $('.overlay').visibility({
                    type: 'fixed',
                    offset: 80
                });

                // lazy load images
                $('.image').visibility({
                    type: 'image',
                    transition: 'vertical flip in',
                    duration: 500
                });

                // show dropdown on hover
                $('.main.menu  .ui.dropdown').dropdown({
                    on: 'hover'
                });
            })
            ;
    </script>
</body>
</html>